### ISSUE TITLE
Vault add some region configuration to specify the way the secrets are injected

### ISSUE THREAD

**Issue by alexisdondon** [InseeFrLab/onyxia-api#409]
To allow the onyxia helm chart to specifigy the mode and then decide to use personal vault token (today behaviour) or use the jwt service account to issue a vault token and then load the var env.

```
vault:
  injection:
     personalToken:
        enabled: true false.
    serviceAccount:
       mode: jwt/kubernete
       enabled: true/false
       pathJwt
       role
```
